### ISSUE TITLE
After setup, it doesn't do anything

### ISSUE THREAD

**Issue by lucius100** [iamrony777/javinfo-api-js#6]
I tried to self host this, after setup it doesn't do anything, is it not working ?

I even navigate to /search also can't access.

**Comment by iamrony777** [comment]
1. Check body payload from [Rapidapi docs](https://rapidapi.com/iamrony777/api/javinfo/)
2. It would be better to use a HTTP Client/API testing platform like Httpie
3. I will recommend to check out [javinfo-api](https://github.com/iamrony777/javinfo-api) (written in python) instead of this repo

Here's an example of payload

![image](https://github.com/iamrony777/javinfo-api-ts/assets/88942925/11f3444f-c939-4700-9a41-be91044c36b1)

**Comment by iamrony777** [comment]
Closed accidentally. Feel free to close this issue yourself.

**Comment by lucius100** [comment]
> 1. Check body payload from [Rapidapi docs](https://rapidapi.com/iamrony777/api/javinfo/)
> 2. It would be better to use a HTTP Client/API testing platform like [Httpie](https://httpie.io/desktop)
> 3. I will recommend to check out [javinfo-api](https://github.com/iamrony777/javinfo-api) (written in python) instead of this repo
> 
> Here's an example of payload
> 
> ![image](https://user-images.githubusercontent.com/88942925/281956840-11f3444f-c939-4700-9a41-be91044c36b1.png)

Yes, javinfo-api working for me, I will use that instead, still in the middle of testing, will open issue on that repo instead of here later.
